modLoader = "javafml"
loaderVersion = "[40,)"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes/issues"

[[mods]]
modId = "friendsandfoes"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"

[[dependencies.friendsandfoes]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "architectury"
mandatory = true
versionRange = "[4.4.60,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.friendsandfoes]]
modId = "cloth_config"
mandatory = false
versionRange = "[6,)"
ordering = "NONE"
side = "CLIENT"
