name: "Build"

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3.5.3
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: "temurin"
                    java-version: 17

            - name: "Initialize caches"
              uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            -   name: "Build with gradle"
                run: ./gradlew build

    run-fabric-client:
        needs: build
        runs-on: ubuntu-latest
        name: "Run fabric client"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3.5.3
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: "temurin"
                    java-version: 17

            - name: "Initialize caches"
              uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            -   name: "Run fabric client"
                uses: modmuss50/xvfb-action@v1
                with:
                    run: ./gradlew fabric:runClient

    run-fabric-server:
        needs: build
        runs-on: ubuntu-latest
        name: "Run fabric server"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3.5.3
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.12.0
                with:
                    distribution: "temurin"
                    java-version: 17

            - name: "Initialize caches"
              uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            -   name: "Accept eula"
                run: mkdir -p fabric/run && echo "eula=true" > fabric/run/eula.txt

            -   name: "Run fabric server"
                run: ./gradlew fabric:runServer --args="nogui"