name: "Build"

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
            - "!master"

jobs:
    build:
        name: "Build project"
        runs-on: ubuntu-latest
        timeout-minutes: 15
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Parse gradle properties"
                id: gradle-properties
                run: ./.github/scripts/parse-gradle-properties.sh

            -   name: "Set up JDK"
                uses: actions/setup-java@v4
                with:
                    java-version: ${{ steps.gradle-properties.outputs.MOD_JAVA_VERSION }}
                    distribution: temurin

            -   name: "Generate matrix for the run job"
                id: set-matrix
                run: ./.github/scripts/generate-run-matrix.sh

            -   name: "Run gradle build"
                uses: gradle/actions/setup-gradle@v3
                with:
                    cache-read-only: false
                    generate-job-summary: false
                    gradle-version: wrapper
                    arguments: build

            -   name: "Upload Built JARs"
                uses: actions/upload-artifact@v4
                with:
                    name: built-jars
                    path: |
                        ./**/build/libs/*.jar

    run:
        name: Run ${{ matrix.mod_loader }} ${{ matrix.script }}
        runs-on: ubuntu-latest
        needs: build
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.build.outputs.matrix)}}
        timeout-minutes: 15

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Download Built JARs"
                uses: actions/download-artifact@v4
                with:
                    name: built-jars
                    path: run/mods

            -   name: "Display structure of downloaded files"
                run: ls -R

            -   name: "Parse gradle properties"
                id: gradle-properties
                run: ./.github/scripts/parse-gradle-properties.sh ${{ matrix.version }}

            -   name: Run ${{ matrix.mod_loader }} ${{ matrix.script }}
                uses: 3arthqu4ke/mc-runtime-test@2.4.0
                with:
                    mc: ${{ matrix.version }}
                    modloader: ${{ matrix.mod_loader }}
                    regex: .*${{ matrix.mod_loader }}.*
                    mc-runtime-test: ${{ matrix.mod_loader }}
                    java: ${{ steps.gradle-properties.outputs.MOD_JAVA_VERSION }}
                    java-distribution: temurin
                    xvfb: false
                    headlessmc-command: -lwjgl --retries 3 --jvm -Djava.awt.headless=true