name: Publish Debugify

on: release

jobs:
    publish:
        if: contains('["isXander", "EthanDevelops", "Wyvest", "raeids"]', github.actor)
        runs-on: ubuntu-latest
        name: Publish to all platforms

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK
              uses: actions/setup-java@v3.3.0
              with:
                  java-version: 17
                  distribution: temurin

            -   name: Build artifacts
                run: ./gradlew build

            -   name: "Release Fabric version to CurseForge"
                uses: Kir-Antipov/mc-publish@v2.1
                with:
                    modrinth-id: YL57xq9U
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    curseforge-id: 551364
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    github-token: ${{ secrets.GITHUB_TOKEN }}

                    files: build/libs/!(*-@(dev|sources|all)).jar

                    version-type: release

                    loaders: fabric

                    dependencies: sodium | depends | *

                    version-resolver: latest

            -   name: "Release Fabric version to Modrinth"
                    uses: Kir-Antipov/mc-publish@v2.1
                    with:
                        modrinth-id: YL57xq9U
                        modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                        curseforge-id: 455508
                        curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                        github-token: ${{ secrets.GITHUB_TOKEN }}

                        files: build/libs/!(*-@(dev|sources|all)).jar

                        version-type: release

                        loaders: fabric

                        dependencies: sodium | depends | *

                        version-resolver: latest