name: "Publish"

on:
    release:
        types: [ published ]

env:
    VERSION_TYPE: release
    JAVA_VERSIONS: |
        Java 17
        Java 18
    FABRIC_DEPENDENCIES: |
        fabric-api | depends | *
        architectury-api | depends | *
    RETRY_ATTEMPTS: 3
    RELAY_DELAY: 10000
    VERSION_RESOLVER: latest

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Build"
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v3

            -   name: "Set up JDK"
                uses: actions/setup-java@v3.3.0
                with:
                    java-version: 17
                    distribution: temurin
                    cache: gradle

            -   name: "Make gradle wrapper executable"
                run: chmod +x ./gradlew

            -   name: "Build with gradle"
                run: ./gradlew clean build --no-daemon --refresh-dependencies --stacktrace

            -   name: "Capture build artifacts"
                uses: actions/upload-artifact@v3.1.0
                with:
                    name: "artifacts"
                    path: |
                        fabric/build/libs/friendsandfoes-fabric-mc1.18.2-1.4.0.jar
                        forge/build/libs/friendsandfoes-forge-mc1.18.2-1.4.0.jar
                        quilt/build/libs/friendsandfoes-quilt-mc1.18.2-1.4.0.jar
                        LICENSE.txt

    publish-license-to-release:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish license to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "artifacts"

            -   name: "Publish license to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: 'LIECENSE.txt'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-github:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to GitHub"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "artifacts"

            -   name: "Publish Fabric to GitHub"
                uses: AButler/upload-release-assets@v2.0
                with:
                    files: 'fabric/build/libs/friendsandfoes-fabric-mc1.18.2-1.4.0.jar'
                    repo-token: ${{ secrets.GITHUB_TOKEN }}

    publish-fabric-to-curseforge:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to CurseForge"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "artifacts"

            -   name: "Publish Fabric to CurseForge"
                uses: Kir-Antipov/mc-publish@v2.1
                with:
                    curseforge-id: 551364
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    files-primary: "fabric/build/libs/friendsandfoes-fabric-mc1.18.2-1.4.0.jar"
                    version-type: $VERSION_TYPE
                    loaders: fabric
                    game-versions: 1.18.2
                    name: "Friends&Foes mc1.18.2-1.4.0 (Fabric)"
                    dependencies: $FABRIC_DEPENDENCIES
                    java: $JAVA_VERSIONS

                    retry-attempts: $RETRY_ATTEMPTS
                    retry-delay: $RETRY_DELAY
                    version-resolver: $VERSION_RESOLVER

    publish-fabric-to-modrinth:
        needs: build
        runs-on: ubuntu-latest
        name: "Publish Fabric to Modrinth"
        timeout-minutes: 30

        steps:
            -   name: "Download artifacts"
                uses: actions/download-artifact@v3.0.0
                with:
                    name: "artifacts"

            -   name: "Publish Fabric to Modrinth"
                uses: Kir-Antipov/mc-publish@v2.1
                with:
                    modrinth-id: YL57xq9U
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    files-primary: "fabric/build/libs/friendsandfoes-fabric-mc1.18.2-1.4.0.jar"
                    version-type: $VERSION_TYPE
                    loaders: fabric
                    game-versions: 1.18.2
                    name: "Friends&Foes mc1.18.2-1.4.0 (Fabric)"
                    dependencies: $FABRIC_DEPENDENCIES
                    java: $JAVA_VERSIONS
                    retry-attempts: $RETRY_ATTEMPTS
                    retry-delay: $RETRY_DELAY
                    version-resolver: $VERSION_RESOLVER