steps:
    -   name: "Set up JDK"
        uses: actions/setup-java@v3.12.0
        with:
            distribution: "temurin"
            java-version: 17

    - name: "Initialize caches"
      uses: actions/cache@v3.3.1
      with:
          path: |
              ~/.gradle/caches
              ~/.gradle/loom-cache
              ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-build-